name: Compile tree-gen
description: Install tools and compile tree-gen
inputs:
  build_type:
    required: true
    description: Is the build a debug or release version
  conan_profile_host:
    required: true
    description: Which conan profile host to use
  conan_profile_build:
    required: false
    description: Which conan profile build to use
    default: 'default'
  shell:
    required: true
    description: Which shell to use for the `run` command

runs:
  using: composite
  steps:
    - name: Install conan
      run: |
        pipx install conan
      shell: ${{ inputs.shell }}
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    - name: Configure and build
      run: |
        conan profile detect --force
        conan_profile=${{ inputs.conan_profile }}
        prh=${{ inputs.conan_profile_host }}
        lowercase_prh=$(echo ${prh} | tr '[:upper:]' '[:lower:]')
        prb=${{ inputs.conan_profile_build }}
        lowercase_prb=$(echo ${prb} | tr '[:upper:]' '[:lower:]')
        conan build . -pr:h=${lowercase_prh} -pr:b=${lowercase_prb} -b missing
      shell: ${{ inputs.shell }}
    - name: Test
      run: ctest -C ${{ inputs.build_type }} --output-on-failure
      shell: ${{ inputs.shell }}
