package:
  name: libqasm
  version: "{{ load_setup_py_data().version }}"

source:
  path: ../../.

build:
  number: 0

requirements:
  build:
    - setuptools
    - swig
    - cmake
    - flex # [not win]
    - bison # [not win]
    #- winflexbison # [win]
  host:
    - conan >=2.0
    - python
    - plumbum
    - delocate # [osx]
  run:
    - python

test:
  imports:
    - libQasm
  source_files:
    - res
    - test
  requires:
    - pytest
  commands:
    - pytest test

about:
  home: https://github.com/QuTech-Delft/libqasm
  license: Apache v2.0
