name: Python tests
description: Install and run tests in Python
inputs:
  shell:
    required: true
    description: Which shell to use for the `run` command

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    - name: Install Python dependencies
      run: |
        pipx install conan pytest 
        pipx inject conan setuptools
      shell: ${{ inputs.shell }}
    - name: Build
      run: python -m pip install --verbose .
      shell: ${{ inputs.shell }}
    - name: Test
      run: python -m pytest
      shell: ${{ inputs.shell }}
