name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  func-gen-cpp-linux-x64:
    name: "Func-gen: C++ tests (gcc-clang/Linux/x64)"
    defaults:
      run:
        working-directory: src/cpp/func-gen
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
        compiler:
          - clang
          - gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/cpp-tests-func-gen
        with:
          build_type: ${{ matrix.build_type }}
          c_compiler: ${{ matrix.c_compiler }}
          cxx_compiler: ${{ matrix.cxx_compiler }}
          conan_profile: tests-${{ matrix.build_type }}-${{ matrix.compiler }}-linux-x64
          shell: bash

  func-gen-cpp-macos-x64:
    name: "Func-gen: C++ tests (clang/MacOS/x64)"
    defaults:
      run:
        working-directory: src/cpp/func-gen
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install bison flex
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
      - uses: ./.github/actions/cpp-tests-func-gen
        with:
          build_type: ${{ matrix.build_type }}
          conan_profile: tests-${{ matrix.build_type }}-apple_clang-macos-x64
          shell: bash

  func-gen-cpp-windows-x64:
    name: "Func-gen: C++ tests (msvc/Windows/x64)"
    defaults:
      run:
        working-directory: src/cpp/func-gen
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey-cpp-0
          restore-keys: |
            ${{ runner.os }}-chocolatey-cpp-
            ${{ runner.os }}-chocolatey-
      - name: Install dependencies
        run: choco install winflexbison3 --version 2.5.24.20210105
      - uses: ./.github/actions/cpp-tests-func-gen
        with:
          build_type: ${{ matrix.build_type }}
          conan_profile: tests-${{ matrix.build_type }}-msvc-windows-x64
          shell: bash

  func-gen-cpp-linux-arm64:
    name: "Func-gen: C++ tests (gcc/Linux/ARM64)"
    defaults:
      run:
        working-directory: src/cpp/func-gen
    runs-on: [self-hosted, ARM64, Linux]
    container: python:3.11
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add Python symlink
        run: ln -sf /usr/local/bin/python3.11 /usr/bin/python3
        shell: bash
      - name: Install bison and flex
        run: |
          apt-get update
          apt-get install -y bison flex
      - uses: ./.github/actions/cpp-tests-func-gen
        with:
          build_type: Release
          conan_profile: tests-${{ matrix.build_type }}-gcc-linux-arm64
          shell: bash

  func-gen-cpp-macos-arm64:
    name: "Func-gen: C++ tests (clang/macos/ARM64)"
    defaults:
      run:
        working-directory: src/cpp/func-gen
    runs-on: [self-hosted, ARM64, macOS]
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bison and flex
        run: |
          brew install bison flex
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
        shell: bash
      - uses: ./.github/actions/cpp-tests-func-gen
        with:
          build_type: Release
          conan_profile: tests-${{ matrix.build_type }}-apple_clang-macos-arm64
          shell: bash
