name: Test

on:
  push:
    branches:
    - master
    - v3
  pull_request:

jobs:
  cpp:
    name: 'C++ tests and examples'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install bison flex
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
    - uses: actions/cache@v3
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-cpp-0
        restore-keys: |
          ${{ runner.os }}-chocolatey-cpp-
          ${{ runner.os }}-chocolatey-
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: choco install winflexbison3 --version 2.5.18.20190508
    - name: Configure
      run: cmake . -DTREE_GEN_BUILD_TESTS=ON
    - name: Build
      run: cmake --build . --parallel
    - name: Test
      run: ctest -C Debug --output-on-failure
